
version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nifi-data:/data
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_SECURITY_USER_AUTHORIZER=file-provider
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=file-provider
      - NIFI_SECURITY_ENABLED=false
    networks:
      - nifi-net
    depends_on:
      - zookeeper
    deploy:
      replicas: 3

  nifi-registry:
    image: apache/nifi-registry:latest
    ports:
      - "18080:18080"
    volumes:
      - ./nifi-registry-data:/data
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
      - NIFI_REGISTRY_WEB_HTTPS_PORT=18443
      - NIFI_REGISTRY_SECURITY_USER_AUTHORIZER=file-provider
      - NIFI_REGISTRY_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=file-provider
      - NIFI_REGISTRY_SECURITY_ENABLED=false
    networks:
      - nifi-net
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper-data:/data
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888
    networks:
      - nifi-net

networks:
  nifi-net:
    driver: bridge